[env:esp32-s3-devkitc-1]
platform = espressif32@6.3.2
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    earlephilhower/ESP8266Audio@1.9.7